# Site
title:              Li zeyu
bio:                'Stay hungry. Stay foolish.'
description:        "I'm a student at present,interested in rendering."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/icon.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://lizeyu.me

encoding: utf-8

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   hungrysharks
comments: true

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              zeyuli0225@gmail.com
#twitter:            username
#facebook:           username
github-url:         hungry0
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
